# Generated by Django 5.0.1 on 2024-02-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
