# Generated by Django 5.0.1 on 2024-02-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='p_name',
            field=models.CharField(max_length=50),
        ),
    ]
